---
# Вызов предварительной роли system-prepare для полноценного запуска текущей роли:
- name: Import system-prepare role for running current role on SUSE family distro
  import_role:
    name: system-prepare
    tasks_from: main

# Создание группы с именем Vault:
- name: Create Transit Vault group on SUSE family distro
  group:
    name: "{{ local_vault_manual_transit_group }}"
    state: present
    gid: 452

# Создание пользователя с именем Vault:
- name: Create Transit Vault user on SUSE family distro
  user:
    name: "{{ local_vault_manual_transit_user }}"
    groups: "{{ local_vault_manual_transit_group }}"
    home: "{{ local_vault_manual_transit_dir_data }}"
    shell: /sbin/nologin
    create_home: true
    append: true
    uid: 452

# Создание нескольких директорий для последующей работы с Vault:
- name: Create Transit Vault directories on SUSE family distro
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ local_vault_manual_transit_dir_mode }}"
    owner: "{{ local_vault_manual_transit_user }}"
    group: "{{ local_vault_manual_transit_group }}"
  loop:
    - {path: "{{ local_vault_manual_transit_dir_config }}"}
    - {path: "{{ local_vault_manual_transit_dir_data }}"}

# Загрузка архива с бинарным файлом Vault из Интернета по прямой ссылке:
- name: Download Transit Vault archive for future installation on SUSE family distro
  get_url:
    url: "{{ local_vault_manual_transit_file_archive_link }}"
    mode: "{{ local_vault_manual_transit_file_mode }}"
    dest: "/tmp/{{ local_vault_manual_transit_file_archive_name }}"
    force: false

# Извлечение архива и перемещение бинарного файла в соответствующую директорию:
- name: Unpack the Transit Vault archive and move the binary file on SUSE family distro
  unarchive:
    src: "/tmp/{{ local_vault_manual_transit_file_archive_name }}"
    dest: "{{ local_vault_manual_transit_path_binary }}"
    remote_src: true

# Копирование всех конфигурационных файлов Vault в режиме работы Transit и их последующая отправка в соответствующие директории:
- name: Copy Transit Vault configuration files from templates on SUSE family distro
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(local_vault_manual_transit_file_mode) }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - src: "templates/{{ local_vault_manual_transit_file_autocomplete_j2 }}"
      dest: "{{ local_vault_manual_transit_file_autocomplete_path }}"
      mode: "{{ local_vault_manual_transit_file_mode }}"
      owner: "{{ local_vault_manual_transit_user }}"
      group: "{{ local_vault_manual_transit_group }}"
    - src: "templates/{{ local_vault_manual_transit_file_config }}.j2"
      dest: "{{ local_vault_manual_transit_dir_config }}/{{ local_vault_manual_transit_file_config }}"
      mode: "{{ local_vault_manual_transit_file_mode }}"
      owner: "{{ local_vault_manual_transit_user }}"
      group: "{{ local_vault_manual_transit_group }}"
    - src: "templates/{{ local_vault_manual_transit_file_systemd }}.j2"
      dest: "/usr/lib/systemd/system/{{ local_vault_manual_transit_file_systemd }}"
      mode: "{{ local_vault_manual_transit_file_mode }}"
      owner: "0"
      group: "0"
  notify: Restart Transit Vault

# Запуск и добавление в автозагрузку сервиса Vault в режиме работы Transit с помощью Systemd:
- name: Start Transit Vault service on SUSE family distro
  service:
    name: vault
    state: started
    enabled: true
    daemon_reload: true
  changed_when: false
