---
# Данный файл используется для преобразования состояния экземпляров в реальное состояние, объявленное в реальных тестируемых ролях:
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    # Данный шаг вызывает роль manual-cluster-vault для последующего прогона system-unseal-cluster-vault:
    - name: "Include manual-cluster-vault role for testing"
      include_role:
        name: "manual-cluster-vault"

    # Добавление интервала по времени для загрузки Vault:
    - name: "Wait 10 second for checking Vault"
      wait_for:
        timeout: 10

    # Данный шаг вызывает роль system-unseal-cluster-vault для прогона тестов с помощью Molecule:
    - name: "Include system-unseal-cluster-vault role for testing"
      include_role:
        name: "system-unseal-cluster-vault"
