---
# Перезапуск сервиса Vault в случае изменения одного из конфигурационных файлов:
- name: Restart Transit Vault
  systemd:
    name: vault
    state: restarted
    enabled: true
    daemon_reload: true
