---
# Данный файл знаменует успешное завершение запускаемых ранее тестов:
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # Добавление интервала по времени для загрузки Consul Agent:
    - name: Wait 10 second for checking Consul
      wait_for:
        timeout: 10

    # Проверка доступности Consul Agent после установки:
    - name: Check Consul Agent for Availability
      uri:
        url: "http://127.0.0.1:{{ global_consul_host_listening_http_port }}"
        method: GET
        timeout: 10
        return_content: false
        validate_certs: false
        status_code: [200]
      when: not global_consul_manual_agent_enable_https | default(false)
