---
# Глобальные переменные, используемые для выполнения роли по развертыванию Manual Cluster Consul:
global_consul_cluster_inventory_group: "consul"
global_consul_cluster_current_version: "1.21.0"
global_consul_cluster_client_address: "0.0.0.0"
global_consul_cluster_http_port: "8500"
global_consul_cluster_https_port: "8443"
global_consul_cluster_dns_port: "8600"
global_consul_cluster_dc_name: "dc1"
global_consul_cluster_server_config: "consul_server_config.hcl.j2"
global_consul_cluster_enable_https: true
global_consul_cluster_enable_tls_incoming: true
global_consul_cluster_enable_tls_outgoing: true
global_consul_cluster_enable_tls_server_hostname: true

# Глобальные переменные, используемые для создания CA и выпуска самоподписных сертификатов:
global_system_internal_delegate_host: "{{ groups[global_consul_cluster_inventory_group | default('consul')] | first }}"
global_system_internal_ca_key_group: "consul"
global_system_internal_ca_key_group_id: 451
global_system_internal_dir_ca: "/opt/consul/tls/ca"
global_system_internal_dir_node_certificates: "/opt/consul/tls"
global_system_internal_file_ca_certificate: "ca.crt.pem"
global_system_internal_file_ca_csr: "ca.csr.pem"
global_system_internal_file_ca_privatekey: "ca.key.pem"
global_system_internal_privatekey_type: "RSA"
global_system_internal_privatekey_size: 4096
global_system_internal_csr_country_name: "US"
global_system_internal_csr_common_name: "Local Consul Certificate Authority"
global_system_internal_csr_organization_name: "Local Consul Entertainment"
global_system_internal_csr_email_address: "admin@consul.internal"
global_system_internal_csr_san_dns:
  - "DNS:*.{{ global_consul_cluster_dc_name }}.consul"
  - "DNS:server.{{ global_consul_cluster_dc_name }}.consul"
  - "DNS:consul-{{ inventory_hostname }}-client"
  - "DNS:consul-{{ inventory_hostname }}-server"
  - "DNS:local.internal"
  - "DNS:*.local.internal"
