---
# Вызов предварительной роли system-prepare для полноценного запуска текущей роли:
- name: Import system-prepare role for running current role on Debian family distro
  import_role:
    name: system-prepare
    tasks_from: main

# Вызов предварительной роли system-internal-certificates для полноценного запуска текущей роли:
- name: Import system-internal-certificates role for running current role on Debian family distro
  import_role:
    name: system-internal-certificates
    tasks_from: main
  when: global_vault_raft_cluster_enable_https | bool

# Создание группы с именем Vault:
- name: Create Cluster Vault group on Debian family distro
  group:
    name: "{{ local_vault_manual_raft_cluster_group }}"
    state: present
    gid: 452

# Создание пользователя с именем Vault:
- name: Create Cluster Vault user on Debian family distro
  user:
    name: "{{ local_vault_manual_raft_cluster_user }}"
    groups: "{{ local_vault_manual_raft_cluster_group }}"
    home: "{{ local_vault_manual_raft_cluster_dir_raft }}"
    shell: /sbin/nologin
    create_home: true
    append: true
    uid: 452

# Создание нескольких директорий для последующей работы с кластером Vault:
- name: Create Cluster Vault directories on Debian family distro
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ local_vault_manual_raft_cluster_dir_mode }}"
    owner: "{{ local_vault_manual_raft_cluster_user }}"
    group: "{{ local_vault_manual_raft_cluster_group }}"
  loop:
    - {path: "{{ local_vault_manual_raft_cluster_dir_config }}"}
    - {path: "{{ local_vault_manual_raft_cluster_dir_raft }}"}

# Загрузка архива с бинарным файлом Vault из Интернета по прямой ссылке:
- name: Download Cluster Vault archive for future installation on Debian family distro
  get_url:
    url: "{{ local_vault_manual_raft_cluster_file_archive_link }}"
    mode: "{{ local_vault_manual_raft_cluster_file_mode }}"
    dest: "/tmp/{{ local_vault_manual_raft_cluster_file_archive_name }}"
    force: false

# Извлечение архива и перемещение бинарного файла в соответствующую директорию:
- name: Unpack the Cluster Vault archive and move the binary file on Debian family distro
  unarchive:
    src: "/tmp/{{ local_vault_manual_raft_cluster_file_archive_name }}"
    dest: "{{ local_vault_manual_raft_cluster_path_binary }}"
    remote_src: true

# Копирование всех конфигурационных файлов Vault и их последующая отправка в соответствующие директории:
- name: Copy Cluster Vault configuration files from templates on Debian family distro
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(local_vault_manual_raft_cluster_file_mode) }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - src: "templates/{{ local_vault_manual_raft_cluster_file_autocomplete_j2 }}"
      dest: "{{ local_vault_manual_raft_cluster_file_autocomplete_path }}"
      mode: "{{ local_vault_manual_raft_cluster_file_mode }}"
      owner: "{{ local_vault_manual_raft_cluster_user }}"
      group: "{{ local_vault_manual_raft_cluster_group }}"
    - src: "templates/{{ lookup('vars', global_vault_raft_cluster_enable_https | ternary('global_vault_raft_cluster_https_config', 'global_vault_raft_cluster_http_config')) }}"
      dest: "{{ local_vault_manual_raft_cluster_dir_config }}/{{ local_vault_manual_raft_cluster_file_config }}"
      mode: "{{ local_vault_manual_raft_cluster_file_mode }}"
      owner: "{{ local_vault_manual_raft_cluster_user }}"
      group: "{{ local_vault_manual_raft_cluster_group }}"
  notify: Restart Cluster Vault

# Копирование Systemd файла из директории templates и его последующая передача в соответствующую директорию:
- name: Copy Cluster Vault systemd config on Debian family distro
  template:
    src: "templates/{{ local_vault_manual_raft_cluster_file_systemd }}.j2"
    dest: "/usr/lib/systemd/system/{{ local_vault_manual_raft_cluster_file_systemd }}"
    mode: "{{ local_vault_manual_raft_cluster_file_mode }}"
    owner: "0"
    group: "0"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' and ansible_distribution_major_version | int == 12
  notify: Restart Cluster Vault

# Копирование Systemd файла из директории templates и его последующая передача в соответствующую директорию:
- name: Copy Cluster Vault systemd config on Debian family distro (Old Debian Versions)
  template:
    src: "templates/{{ local_vault_manual_raft_cluster_file_systemd }}.j2"
    dest: "/etc/systemd/system/{{ local_vault_manual_raft_cluster_file_systemd }}"
    mode: "{{ local_vault_manual_raft_cluster_file_mode }}"
    owner: "0"
    group: "0"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version | int != 12
  notify: Restart Cluster Vault

# Запуск и добавление в автозагрузку сервиса Vault с помощью Systemd:
- name: Start Cluster Vault service on Debian family distro
  service:
    name: vault
    state: started
    enabled: true
    daemon_reload: true

# - name: Check that the certificate has been added on Debian family distro
#   shell: |
#     openssl s_client -connect 127.0.0.1:{{ global_vault_host_listening_port }} -CAfile {{ global_vault_system_internal_dir_node_certificates }}/{{ global_vault_system_internal_file_ca_certificate }}
#   register: openssl_check
#   failed_when: "'Verification: OK' not in openssl_check.stdout"
#   when: global_vault_raft_cluster_enable_https | bool

# - name: Output the result on Debian family distro
#   debug:
#     msg: "{{ openssl_check.stdout }}"
#   when: global_vault_raft_cluster_enable_https | bool
