---
# Вызов предварительной роли system-prepare для полноценного запуска текущей роли:
- name: Import system-prepare role for running current role on Debian family distro
  import_role:
    name: system-prepare
    tasks_from: main

# Создание в системе группы с именем Vault:
- name: Create Vault group on Debian family distro
  group:
    name: "{{ vault_user_and_group }}"
    state: present
    gid: 452

# Создание в системе пользователя с именем Vault:
- name: Create Vault user on Debian family distro
  user:
    name: "{{ vault_user_and_group }}"
    groups: "{{ vault_user_and_group }}"
    home: "{{ vault_raft_dir }}"
    shell: /sbin/nologin
    create_home: true
    append: true
    uid: 452

# Создание нескольких директорий для последующей работы с Vault:
- name: Create Vault directories on Debian family distro
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ vault_dir_mode }}"
    owner: "{{ vault_user_and_group }}"
    group: "{{ vault_user_and_group }}"
    recurse: true
  with_items:
    - {path: "{{ vault_config_dir }}"}
    - {path: "{{ vault_raft_dir }}"}
  changed_when: false

# Загрузка архива с бинарным файлом Vault из Интернета по прямой ссылке:
- name: Download Vault binary file for future installation on Debian family distro
  get_url:
    url: "{{ vault_binary_file }}"
    mode: "{{ vault_file_mode }}"
    dest: "/tmp/vault.zip"

# Распаковка архива и перемещение бинарного файла в соответствующую директорию:
- name: Unpack the archive and move the Vault binary file on Debian family distro
  unarchive:
    src: "/tmp/vault.zip"
    dest: "{{ vault_binary_path }}"
    remote_src: true

# Копирование файла из директории files и его последующая передача в директорию Bash Completion:
- name: Copy bash completion file for Vault on Debian family distro
  template:
    src: "templates/{{ vault_autocomplete_j2 }}"
    dest: "{{ vault_autocomplete_file }}"
    mode: "{{ vault_file_mode }}"
    owner: "{{ vault_user_and_group }}"
    group: "{{ vault_user_and_group }}"

# Обновление терминальной сессии для последующего использования автодополнения:
- name: Update source on Debian family distro
  shell: source "{{ vault_autocomplete_file }}"
  args:
    executable: /bin/bash
  changed_when: false

# Копирование конфигурационного файла из директории templates и его последующая передача в рабочую директорию Vault:
- name: Copy Vault config file in config directory on Debian family distro
  template:
    src: "templates/{{ vault_raft_cluster_enable_https_config | ternary('vault_raft_cluster_https_config', 'vault_raft_cluster_http_config') }}.j2"
    dest: "{{ vault_config_dir }}/{{ vault_config_file }}"
    mode: "{{ vault_file_mode }}"
    owner: "{{ vault_user_and_group }}"
    group: "{{ vault_user_and_group }}"
  changed_when: false

# Копирование Systemd файла из директории templates и его последующая передача в соответствующую директорию:
- name: Copy Vault systemd config on Debian family distro
  template:
    src: "templates/{{ vault_systemd_file }}.j2"
    dest: "/usr/lib/systemd/system/{{ vault_systemd_file }}"
    mode: "{{ vault_file_mode }}"
    owner: "0"
    group: "0"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' and ansible_distribution_major_version | int == 12

# Копирование Systemd файла из директории templates и его последующая передача в соответствующую директорию:
- name: Copy Vault systemd config on Debian family distro (Old Debian Versions)
  template:
    src: "templates/{{ vault_systemd_file }}.j2"
    dest: "/etc/systemd/system/{{ vault_systemd_file }}"
    mode: "{{ vault_file_mode }}"
    owner: "0"
    group: "0"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' and ansible_distribution_major_version | int != 12

# Запуск и добавление в автозагрузку сервиса Vault с помощью Systemd:
- name: Start Vault service on Debian family distro
  service:
    name: vault
    state: started
    enabled: true
    daemon_reload: true
