---
# Данный файл знаменует успешное завершение запускаемых ранее тестов:
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # Добавление интервала по времени для загрузки Vault:
    - name: Wait 10 second for checking Vault
      wait_for:
        timeout: 10

    # Проверка доступности Vault после установки:
    - name: Check Vault for Availability
      uri:
        url: "{{ (global_vault_cluster_enable_https | bool) | ternary('https', 'http') }}://127.0.0.1:{{ global_vault_host_listening_port }}"
        method: GET
        timeout: 10
        return_content: false
        validate_certs: false
        status_code: [200]
