---
# Данный файл знаменует успешное завершение запускаемых ранее тестов:
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # Добавление интервала по времени для загрузки Consul:
    - name: Wait 10 second for checking Consul
      wait_for:
        timeout: 10

    # Проверка доступности Consul после установки:
    - name: Check Consul for Availability
      uri:
        url: >-
          {{
            ( 'https' if global_consul_cluster_enable_https else 'http' ) ~ '://127.0.0.1:' ~
            ( global_consul_host_listening_https_port if global_consul_cluster_enable_https else global_consul_host_listening_http_port ) ~
            '/v1/status/leader'
          }}
        method: GET
        timeout: 10
        return_content: false
        status_code: [200]
        validate_certs: "{{ global_consul_cluster_enable_https }}"
        client_cert: >-
          {{ (global_system_internal_dir_node_certificates ~ '/' ~ inventory_hostname ~ '.crt.pem') if global_consul_cluster_enable_https else omit }}
        client_key: >-
          {{ (global_system_internal_dir_node_certificates ~ '/' ~ inventory_hostname ~ '.key.pem') if global_consul_cluster_enable_https else omit }}
        ca_path: >-
          {{ (global_system_internal_dir_node_certificates ~ '/' ~ global_system_internal_file_ca_certificate) if global_consul_cluster_enable_https else omit }}
