---
# Вызов предварительной роли system-prepare для полноценного запуска текущей роли:
- name: Import system-prepare role for running current role on RedHat family distro
  import_role:
    name: system-prepare
    tasks_from: main

# Создание группы с именем Vault:
- name: Create Vault group on RedHat family distro
  group:
    name: "{{ local_vault_manual_group }}"
    state: present
    gid: 452

# Создание пользователя с именем Vault:
- name: Create Vault user on RedHat family distro
  user:
    name: "{{ local_vault_manual_user }}"
    groups: "{{ local_vault_manual_group }}"
    home: "{{ local_vault_manual_dir_data }}"
    shell: /sbin/nologin
    create_home: true
    append: true
    uid: 452

# Создание нескольких директорий для последующей работы с Vault:
- name: Create Vault directories on RedHat family distro
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ local_vault_manual_dir_mode }}"
    owner: "{{ local_vault_manual_user }}"
    group: "{{ local_vault_manual_group }}"
  loop:
    - {path: "{{ local_vault_manual_dir_config }}"}
    - {path: "{{ local_vault_manual_dir_data }}"}
    - {path: "{{ local_vault_manual_dir_tls }}"}

# Загрузка архива с бинарным файлом Vault из Интернета по прямой ссылке:
- name: Download Vault archive for future installation on RedHat family distro
  get_url:
    url: "{{ local_vault_manual_file_archive_link }}"
    mode: "{{ local_vault_manual_file_mode }}"
    dest: "/tmp/{{ local_vault_manual_file_archive_name }}"
    force: true

# Извлечение архива и перемещение бинарного файла в соответствующую директорию:
- name: Unpack the Vault archive and move the binary file on RedHat family distro
  unarchive:
    src: "/tmp/{{ local_vault_manual_file_archive_name }}"
    dest: "{{ local_vault_manual_path_binary }}"
    remote_src: true

# Копирование всех конфигурационных файлов Vault и их последующая отправка в соответствующие директории:
- name: Copy Vault configuration files from templates on RedHat family distro
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(local_vault_manual_file_mode) }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - src: "templates/{{ local_vault_manual_file_autocomplete_j2 }}"
      dest: "{{ local_vault_manual_file_autocomplete_path }}"
      mode: "{{ local_vault_manual_file_mode }}"
      owner: "{{ local_vault_manual_user }}"
      group: "{{ local_vault_manual_group }}"
    - src: "templates/{{ local_vault_manual_file_config }}.j2"
      dest: "{{ local_vault_manual_dir_config }}/{{ local_vault_manual_file_config }}"
      mode: "{{ local_vault_manual_file_mode }}"
      owner: "{{ local_vault_manual_user }}"
      group: "{{ local_vault_manual_group }}"
    - src: "templates/{{ local_vault_manual_file_systemd }}.j2"
      dest: "/usr/lib/systemd/system/{{ local_vault_manual_file_systemd }}"
      mode: "{{ local_vault_manual_file_mode }}"
      owner: "0"
      group: "0"
  notify: Restart Vault

# Запуск и добавление в автозагрузку сервиса Vault с помощью Systemd:
- name: Start Vault service on RedHat family distro
  service:
    name: vault
    state: started
    enabled: true
    daemon_reload: true
