variable "name" {
  description = "Name of the identity entity"
  type        = string
}

variable "policies" {
  description = "List of Vault policies attached directly to this entity. Prefer assigning policies via groups"
  type        = list(string)
  default     = []
}

variable "metadata" {
  description = "Map of metadata key-value pairs attached to this entity. E.g. { team = 'ops', env = 'prod' }"
  type        = map(string)
  default     = {}
}

variable "disabled" {
  description = "Disable the entity — all tokens generated by its aliases will be rejected"
  type        = bool
  default     = false
}

variable "aliases" {
  description = "List of auth backend aliases for this entity. name = identity in the auth backend (e.g. username for userpass), mount_accessor = accessor of the auth backend"
  type = list(object({
    name           = string
    mount_accessor = string
  }))
  default = []
}
