---
# Данный файл знаменует об успешном завершении запускаемых ранее тестов в Molecule:
- name: Verify our tests in Molecule
  hosts: all
  tasks:
    - name: Output the final result
      assert:
        that: true
