---
# Вызов роли для последующей установки и настройки Manual Consul Cluster для группы серверов на удаленных узлах:
- name: Install and configure Manual Consul Cluster on remote hosts
  gather_facts: true
  become: true
  become_method: sudo
  hosts:
    - all

  # Вызов непосредственно самой роли Manual Consul Cluster для последующего развертывания кластера Consul в системе:
  roles:
    - manual-cluster-consul

  # Информирование о том, что Manual Consul Cluster был успешно установлен в системе:
  post_tasks:
    - name: Information about the successful completion of the playbook
      debug:
        msg:
          - "Your Manual Consul Cluster has been successfully installed on the each system"
