---
# Вызов роли для последующей установки и настройки Manual Cluster Vault на базе Raft для группы серверов на удаленных узлах:
- name: Install and configure Manual Cluster Vault on Raft on remote hosts
  gather_facts: true
  become: true
  become_method: sudo
  hosts:
    - all

  # Вызов непосредственно самой роли Manual Cluster Vault на базе Raft для последующего развертывания кластера Vault в системе:
  roles:
    - manual-cluster-raft-vault

  # Информирование о том, что Manual Cluster Vault на базе Raft был успешно установлен в системе:
  post_tasks:
    - name: Information about the successful completion of the playbook
      debug:
        msg:
          - "Your Manual Cluster Vault on Raft has been successfully installed on the each system"
