---
# Вызов роли с целью создания самоподписных сертификатов для последующего развертывания кластера Vault для работы по HTTPS на удаленных узлах:
- name: Init and Unseal Single Vault on remote hosts
  gather_facts: true
  become: true
  become_method: sudo
  hosts:
    - all

  # Вызов непосредственно самой роли System Internal Certificates для последующего развертывания кластера Vault для работы по HTTPS:
  roles:
    - system-internal-certificates

  # Информирование о том, что все сертификаты были успешно созданы и выпущены самоподписным CA:
  post_tasks:
    - name: Information about the successful completion of the playbook
      debug:
        msg:
          - "Your Self-signed certificates has been successfully created on the system"
