---
# Данный файл используется для преобразования состояния экземпляров в реальное состояние, объявленное в реальных тестируемых ролях:
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  tasks:
    # Данный шаг вызывает роль system-internal-certificates для прогона тестов с помощью Molecule:
    - name: "Include system-internal-certificates role for testing"
      include_role:
        name: "system-internal-certificates"
