---
# Переменные, необходимые для получения сертификатов, относящихся к кластеру Consul (только при его использовании), применимые ко всем дистрибутивам в равной степени:
external_consul_manual_cluster_file_ca_certificate: "consul-ca.crt.pem"
external_consul_manual_cluster_file_ca_private_key: "consul-ca.key.pem"
external_consul_manual_cluster_file_ca_node_value: "consul-{{ inventory_hostname }}"
external_consul_manual_cluster_file_ca_node_value_file_mode: "0640"
external_consul_manual_cluster_file_ca_node_value_dir_mode: "0755"
external_consul_manual_cluster_file_ca_node_value_owner: "root"
external_consul_manual_cluster_vault_tls_dir: "/opt/vault/tls"

# Переменные, необходимые для установки и настройки Manual Cluster Vault, применимые ко всем дистрибутивам в равной степени:
local_vault_manual_cluster_dir_mode: "0755"
local_vault_manual_cluster_dir_config: "/etc/vault.d"
local_vault_manual_cluster_dir_data: "/opt/vault/data"
local_vault_manual_cluster_file_mode: "0640"
local_vault_manual_cluster_file_archive_link: "https://releases.hashicorp.com/vault/{{ global_vault_current_version }}/vault_{{ global_vault_current_version }}_linux_amd64.zip"
local_vault_manual_cluster_file_archive_name: "vault.zip"
local_vault_manual_cluster_file_autocomplete_j2: "vault_autocomplete.j2"
local_vault_manual_cluster_file_autocomplete_path: "/etc/bash_completion.d/vault"
local_vault_manual_cluster_file_config: "config.hcl"
local_vault_manual_cluster_file_systemd: "vault.service"
local_vault_manual_cluster_path_binary: "/usr/local/bin"
local_vault_manual_cluster_user: "vault"
local_vault_manual_cluster_group: "vault"
local_vault_manual_cluster_group_id: 452

# Переменные, необходимые для установки и настройки Manual Cluster Vault для дистрибутивов семейства SUSE:

# Переменные, необходимые для установки и настройки Manual Cluster Vault для дистрибутивов семейства RedHat:

# Переменные, необходимые для установки и настройки Manual Cluster Vault для дистрибутивов семейства Debian:
