---
# Данный файл используется для преобразования состояния экземпляров в реальное состояние, объявленное в реальных тестируемых ролях:
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  tasks:
    # Данный шаг вызывает роль manual-cluster-vault для прогона тестов с помощью Molecule:
    - name: "Include manual-cluster-vault role for testing"
      include_role:
        name: "manual-cluster-vault"
